#spring:
#  mvc:
#    static-path-pattern: /res/**
#  web:
#    resources:
#      static-locations: [classpath:/static/]

# Rest style
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true